// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentResp.proto

package com.bhz.eps.msg;

public final class PaymentRespProto {
  private PaymentRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PaymentRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PaymentResp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    boolean hasStationCode();
    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    java.lang.String getStationCode();
    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getStationCodeBytes();

    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    boolean hasNozzleNumber();
    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    java.lang.String getNozzleNumber();
    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getNozzleNumberBytes();

    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    boolean hasWorkOrder();
    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    java.lang.String getWorkOrder();
    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getWorkOrderBytes();

    /**
     * <code>optional int32 paymentState = 4;</code>
     *
     * <pre>
     *支付状态
     * </pre>
     */
    boolean hasPaymentState();
    /**
     * <code>optional int32 paymentState = 4;</code>
     *
     * <pre>
     *支付状态
     * </pre>
     */
    int getPaymentState();

    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code PaymentResp}
   */
  public static final class PaymentResp extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:PaymentResp)
      PaymentRespOrBuilder {
    // Use PaymentResp.newBuilder() to construct.
    private PaymentResp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PaymentResp(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final PaymentResp defaultInstance;
    public static PaymentResp getDefaultInstance() {
      return defaultInstance;
    }

    public PaymentResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private PaymentResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stationCode_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nozzleNumber_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              workOrder_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              paymentState_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PaymentResp> PARSER =
        new com.google.protobuf.AbstractParser<PaymentResp>() {
      public PaymentResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATIONCODE_FIELD_NUMBER = 1;
    private java.lang.Object stationCode_;
    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    public boolean hasStationCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    public java.lang.String getStationCode() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stationCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stationCode = 1;</code>
     *
     * <pre>
     *油站编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStationCodeBytes() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOZZLENUMBER_FIELD_NUMBER = 2;
    private java.lang.Object nozzleNumber_;
    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    public boolean hasNozzleNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    public java.lang.String getNozzleNumber() {
      java.lang.Object ref = nozzleNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nozzleNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nozzleNumber = 2;</code>
     *
     * <pre>
     *油枪编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNozzleNumberBytes() {
      java.lang.Object ref = nozzleNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nozzleNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKORDER_FIELD_NUMBER = 3;
    private java.lang.Object workOrder_;
    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    public boolean hasWorkOrder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    public java.lang.String getWorkOrder() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          workOrder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string workOrder = 3;</code>
     *
     * <pre>
     *订单编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWorkOrderBytes() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMENTSTATE_FIELD_NUMBER = 4;
    private int paymentState_;
    /**
     * <code>optional int32 paymentState = 4;</code>
     *
     * <pre>
     *支付状态
     * </pre>
     */
    public boolean hasPaymentState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 paymentState = 4;</code>
     *
     * <pre>
     *支付状态
     * </pre>
     */
    public int getPaymentState() {
      return paymentState_;
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 5;</code>
     *
     * <pre>
     *附加信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      stationCode_ = "";
      nozzleNumber_ = "";
      workOrder_ = "";
      paymentState_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNozzleNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, paymentState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNozzleNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, paymentState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.eps.msg.PaymentRespProto.PaymentResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PaymentResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.eps.msg.PaymentRespProto.PaymentResp, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:PaymentResp)
        com.bhz.eps.msg.PaymentRespProto.PaymentRespOrBuilder {
      // Construct using com.bhz.eps.msg.PaymentRespProto.PaymentResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stationCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nozzleNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        workOrder_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        paymentState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp getDefaultInstanceForType() {
        return com.bhz.eps.msg.PaymentRespProto.PaymentResp.getDefaultInstance();
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp build() {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp buildPartial() {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp result = new com.bhz.eps.msg.PaymentRespProto.PaymentResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stationCode_ = stationCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nozzleNumber_ = nozzleNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workOrder_ = workOrder_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.paymentState_ = paymentState_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.eps.msg.PaymentRespProto.PaymentResp other) {
        if (other == com.bhz.eps.msg.PaymentRespProto.PaymentResp.getDefaultInstance()) return this;
        if (other.hasStationCode()) {
          bitField0_ |= 0x00000001;
          stationCode_ = other.stationCode_;
          
        }
        if (other.hasNozzleNumber()) {
          bitField0_ |= 0x00000002;
          nozzleNumber_ = other.nozzleNumber_;
          
        }
        if (other.hasWorkOrder()) {
          bitField0_ |= 0x00000004;
          workOrder_ = other.workOrder_;
          
        }
        if (other.hasPaymentState()) {
          setPaymentState(other.getPaymentState());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000010;
          msg_ = other.msg_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.eps.msg.PaymentRespProto.PaymentResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationCode_ = "";
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public boolean hasStationCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public java.lang.String getStationCode() {
        java.lang.Object ref = stationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stationCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStationCodeBytes() {
        java.lang.Object ref = stationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public Builder setStationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public Builder clearStationCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationCode_ = getDefaultInstance().getStationCode();
        
        return this;
      }
      /**
       * <code>optional string stationCode = 1;</code>
       *
       * <pre>
       *油站编号
       * </pre>
       */
      public Builder setStationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }

      private java.lang.Object nozzleNumber_ = "";
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public boolean hasNozzleNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public java.lang.String getNozzleNumber() {
        java.lang.Object ref = nozzleNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nozzleNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNozzleNumberBytes() {
        java.lang.Object ref = nozzleNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nozzleNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public Builder setNozzleNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nozzleNumber_ = value;
        
        return this;
      }
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public Builder clearNozzleNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nozzleNumber_ = getDefaultInstance().getNozzleNumber();
        
        return this;
      }
      /**
       * <code>optional string nozzleNumber = 2;</code>
       *
       * <pre>
       *油枪编号
       * </pre>
       */
      public Builder setNozzleNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nozzleNumber_ = value;
        
        return this;
      }

      private java.lang.Object workOrder_ = "";
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public boolean hasWorkOrder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public java.lang.String getWorkOrder() {
        java.lang.Object ref = workOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            workOrder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWorkOrderBytes() {
        java.lang.Object ref = workOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public Builder setWorkOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public Builder clearWorkOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workOrder_ = getDefaultInstance().getWorkOrder();
        
        return this;
      }
      /**
       * <code>optional string workOrder = 3;</code>
       *
       * <pre>
       *订单编号
       * </pre>
       */
      public Builder setWorkOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }

      private int paymentState_ ;
      /**
       * <code>optional int32 paymentState = 4;</code>
       *
       * <pre>
       *支付状态
       * </pre>
       */
      public boolean hasPaymentState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 paymentState = 4;</code>
       *
       * <pre>
       *支付状态
       * </pre>
       */
      public int getPaymentState() {
        return paymentState_;
      }
      /**
       * <code>optional int32 paymentState = 4;</code>
       *
       * <pre>
       *支付状态
       * </pre>
       */
      public Builder setPaymentState(int value) {
        bitField0_ |= 0x00000008;
        paymentState_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 paymentState = 4;</code>
       *
       * <pre>
       *支付状态
       * </pre>
       */
      public Builder clearPaymentState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        paymentState_ = 0;
        
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       *
       * <pre>
       *附加信息
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PaymentResp)
    }

    static {
      defaultInstance = new PaymentResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PaymentResp)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
