// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/data/PaymentReq.proto

package com.bhz.eps.msg;

public final class PaymentReqProto {
  private PaymentReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PaymentReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PaymentReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string stationCode = 1;</code>
     */
    boolean hasStationCode();
    /**
     * <code>required string stationCode = 1;</code>
     */
    java.lang.String getStationCode();
    /**
     * <code>required string stationCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStationCodeBytes();

    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    boolean hasNozzleNumber();
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    int getNozzleNumber();

    /**
     * <code>required string workOrder = 3;</code>
     */
    boolean hasWorkOrder();
    /**
     * <code>required string workOrder = 3;</code>
     */
    java.lang.String getWorkOrder();
    /**
     * <code>required string workOrder = 3;</code>
     */
    com.google.protobuf.ByteString
        getWorkOrderBytes();

    /**
     * <code>required int32 paymentMethod = 4;</code>
     */
    boolean hasPaymentMethod();
    /**
     * <code>required int32 paymentMethod = 4;</code>
     */
    int getPaymentMethod();

    /**
     * <code>required int32 preferentialMethod = 5;</code>
     */
    boolean hasPreferentialMethod();
    /**
     * <code>required int32 preferentialMethod = 5;</code>
     */
    int getPreferentialMethod();

    /**
     * <code>required string points = 6;</code>
     */
    boolean hasPoints();
    /**
     * <code>required string points = 6;</code>
     */
    java.lang.String getPoints();
    /**
     * <code>required string points = 6;</code>
     */
    com.google.protobuf.ByteString
        getPointsBytes();

    /**
     * <code>required string receivables = 7;</code>
     */
    boolean hasReceivables();
    /**
     * <code>required string receivables = 7;</code>
     */
    java.lang.String getReceivables();
    /**
     * <code>required string receivables = 7;</code>
     */
    com.google.protobuf.ByteString
        getReceivablesBytes();

    /**
     * <code>required string proceeds = 8;</code>
     */
    boolean hasProceeds();
    /**
     * <code>required string proceeds = 8;</code>
     */
    java.lang.String getProceeds();
    /**
     * <code>required string proceeds = 8;</code>
     */
    com.google.protobuf.ByteString
        getProceedsBytes();
  }
  /**
   * Protobuf type {@code PaymentReq}
   */
  public static final class PaymentReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:PaymentReq)
      PaymentReqOrBuilder {
    // Use PaymentReq.newBuilder() to construct.
    private PaymentReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PaymentReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final PaymentReq defaultInstance;
    public static PaymentReq getDefaultInstance() {
      return defaultInstance;
    }

    public PaymentReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private PaymentReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stationCode_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nozzleNumber_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              workOrder_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              paymentMethod_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              preferentialMethod_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              points_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              receivables_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              proceeds_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PaymentReq> PARSER =
        new com.google.protobuf.AbstractParser<PaymentReq>() {
      public PaymentReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATIONCODE_FIELD_NUMBER = 1;
    private java.lang.Object stationCode_;
    /**
     * <code>required string stationCode = 1;</code>
     */
    public boolean hasStationCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string stationCode = 1;</code>
     */
    public java.lang.String getStationCode() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stationCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stationCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStationCodeBytes() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOZZLENUMBER_FIELD_NUMBER = 2;
    private int nozzleNumber_;
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    public boolean hasNozzleNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    public int getNozzleNumber() {
      return nozzleNumber_;
    }

    public static final int WORKORDER_FIELD_NUMBER = 3;
    private java.lang.Object workOrder_;
    /**
     * <code>required string workOrder = 3;</code>
     */
    public boolean hasWorkOrder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string workOrder = 3;</code>
     */
    public java.lang.String getWorkOrder() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          workOrder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string workOrder = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWorkOrderBytes() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMENTMETHOD_FIELD_NUMBER = 4;
    private int paymentMethod_;
    /**
     * <code>required int32 paymentMethod = 4;</code>
     */
    public boolean hasPaymentMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 paymentMethod = 4;</code>
     */
    public int getPaymentMethod() {
      return paymentMethod_;
    }

    public static final int PREFERENTIALMETHOD_FIELD_NUMBER = 5;
    private int preferentialMethod_;
    /**
     * <code>required int32 preferentialMethod = 5;</code>
     */
    public boolean hasPreferentialMethod() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 preferentialMethod = 5;</code>
     */
    public int getPreferentialMethod() {
      return preferentialMethod_;
    }

    public static final int POINTS_FIELD_NUMBER = 6;
    private java.lang.Object points_;
    /**
     * <code>required string points = 6;</code>
     */
    public boolean hasPoints() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string points = 6;</code>
     */
    public java.lang.String getPoints() {
      java.lang.Object ref = points_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          points_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string points = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPointsBytes() {
      java.lang.Object ref = points_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        points_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVABLES_FIELD_NUMBER = 7;
    private java.lang.Object receivables_;
    /**
     * <code>required string receivables = 7;</code>
     */
    public boolean hasReceivables() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string receivables = 7;</code>
     */
    public java.lang.String getReceivables() {
      java.lang.Object ref = receivables_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receivables_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receivables = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReceivablesBytes() {
      java.lang.Object ref = receivables_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receivables_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCEEDS_FIELD_NUMBER = 8;
    private java.lang.Object proceeds_;
    /**
     * <code>required string proceeds = 8;</code>
     */
    public boolean hasProceeds() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string proceeds = 8;</code>
     */
    public java.lang.String getProceeds() {
      java.lang.Object ref = proceeds_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          proceeds_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string proceeds = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProceedsBytes() {
      java.lang.Object ref = proceeds_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proceeds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      stationCode_ = "";
      nozzleNumber_ = 0;
      workOrder_ = "";
      paymentMethod_ = 0;
      preferentialMethod_ = 0;
      points_ = "";
      receivables_ = "";
      proceeds_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStationCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNozzleNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorkOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaymentMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPreferentialMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPoints()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceivables()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProceeds()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, nozzleNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, paymentMethod_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, preferentialMethod_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPointsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getReceivablesBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getProceedsBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nozzleNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, paymentMethod_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, preferentialMethod_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPointsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getReceivablesBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getProceedsBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentReqProto.PaymentReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.eps.msg.PaymentReqProto.PaymentReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PaymentReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.eps.msg.PaymentReqProto.PaymentReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:PaymentReq)
        com.bhz.eps.msg.PaymentReqProto.PaymentReqOrBuilder {
      // Construct using com.bhz.eps.msg.PaymentReqProto.PaymentReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stationCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nozzleNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        workOrder_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        paymentMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        preferentialMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        points_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        receivables_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        proceeds_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.eps.msg.PaymentReqProto.PaymentReq getDefaultInstanceForType() {
        return com.bhz.eps.msg.PaymentReqProto.PaymentReq.getDefaultInstance();
      }

      public com.bhz.eps.msg.PaymentReqProto.PaymentReq build() {
        com.bhz.eps.msg.PaymentReqProto.PaymentReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.eps.msg.PaymentReqProto.PaymentReq buildPartial() {
        com.bhz.eps.msg.PaymentReqProto.PaymentReq result = new com.bhz.eps.msg.PaymentReqProto.PaymentReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stationCode_ = stationCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nozzleNumber_ = nozzleNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workOrder_ = workOrder_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.paymentMethod_ = paymentMethod_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.preferentialMethod_ = preferentialMethod_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.points_ = points_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.receivables_ = receivables_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.proceeds_ = proceeds_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.eps.msg.PaymentReqProto.PaymentReq other) {
        if (other == com.bhz.eps.msg.PaymentReqProto.PaymentReq.getDefaultInstance()) return this;
        if (other.hasStationCode()) {
          bitField0_ |= 0x00000001;
          stationCode_ = other.stationCode_;
          
        }
        if (other.hasNozzleNumber()) {
          setNozzleNumber(other.getNozzleNumber());
        }
        if (other.hasWorkOrder()) {
          bitField0_ |= 0x00000004;
          workOrder_ = other.workOrder_;
          
        }
        if (other.hasPaymentMethod()) {
          setPaymentMethod(other.getPaymentMethod());
        }
        if (other.hasPreferentialMethod()) {
          setPreferentialMethod(other.getPreferentialMethod());
        }
        if (other.hasPoints()) {
          bitField0_ |= 0x00000020;
          points_ = other.points_;
          
        }
        if (other.hasReceivables()) {
          bitField0_ |= 0x00000040;
          receivables_ = other.receivables_;
          
        }
        if (other.hasProceeds()) {
          bitField0_ |= 0x00000080;
          proceeds_ = other.proceeds_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStationCode()) {
          
          return false;
        }
        if (!hasNozzleNumber()) {
          
          return false;
        }
        if (!hasWorkOrder()) {
          
          return false;
        }
        if (!hasPaymentMethod()) {
          
          return false;
        }
        if (!hasPreferentialMethod()) {
          
          return false;
        }
        if (!hasPoints()) {
          
          return false;
        }
        if (!hasReceivables()) {
          
          return false;
        }
        if (!hasProceeds()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.eps.msg.PaymentReqProto.PaymentReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.eps.msg.PaymentReqProto.PaymentReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationCode_ = "";
      /**
       * <code>required string stationCode = 1;</code>
       */
      public boolean hasStationCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public java.lang.String getStationCode() {
        java.lang.Object ref = stationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stationCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStationCodeBytes() {
        java.lang.Object ref = stationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder setStationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder clearStationCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationCode_ = getDefaultInstance().getStationCode();
        
        return this;
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder setStationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }

      private int nozzleNumber_ ;
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public boolean hasNozzleNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public int getNozzleNumber() {
        return nozzleNumber_;
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public Builder setNozzleNumber(int value) {
        bitField0_ |= 0x00000002;
        nozzleNumber_ = value;
        
        return this;
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public Builder clearNozzleNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nozzleNumber_ = 0;
        
        return this;
      }

      private java.lang.Object workOrder_ = "";
      /**
       * <code>required string workOrder = 3;</code>
       */
      public boolean hasWorkOrder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public java.lang.String getWorkOrder() {
        java.lang.Object ref = workOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            workOrder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWorkOrderBytes() {
        java.lang.Object ref = workOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder setWorkOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder clearWorkOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workOrder_ = getDefaultInstance().getWorkOrder();
        
        return this;
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder setWorkOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }

      private int paymentMethod_ ;
      /**
       * <code>required int32 paymentMethod = 4;</code>
       */
      public boolean hasPaymentMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 paymentMethod = 4;</code>
       */
      public int getPaymentMethod() {
        return paymentMethod_;
      }
      /**
       * <code>required int32 paymentMethod = 4;</code>
       */
      public Builder setPaymentMethod(int value) {
        bitField0_ |= 0x00000008;
        paymentMethod_ = value;
        
        return this;
      }
      /**
       * <code>required int32 paymentMethod = 4;</code>
       */
      public Builder clearPaymentMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        paymentMethod_ = 0;
        
        return this;
      }

      private int preferentialMethod_ ;
      /**
       * <code>required int32 preferentialMethod = 5;</code>
       */
      public boolean hasPreferentialMethod() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 preferentialMethod = 5;</code>
       */
      public int getPreferentialMethod() {
        return preferentialMethod_;
      }
      /**
       * <code>required int32 preferentialMethod = 5;</code>
       */
      public Builder setPreferentialMethod(int value) {
        bitField0_ |= 0x00000010;
        preferentialMethod_ = value;
        
        return this;
      }
      /**
       * <code>required int32 preferentialMethod = 5;</code>
       */
      public Builder clearPreferentialMethod() {
        bitField0_ = (bitField0_ & ~0x00000010);
        preferentialMethod_ = 0;
        
        return this;
      }

      private java.lang.Object points_ = "";
      /**
       * <code>required string points = 6;</code>
       */
      public boolean hasPoints() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string points = 6;</code>
       */
      public java.lang.String getPoints() {
        java.lang.Object ref = points_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            points_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string points = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPointsBytes() {
        java.lang.Object ref = points_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          points_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string points = 6;</code>
       */
      public Builder setPoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        points_ = value;
        
        return this;
      }
      /**
       * <code>required string points = 6;</code>
       */
      public Builder clearPoints() {
        bitField0_ = (bitField0_ & ~0x00000020);
        points_ = getDefaultInstance().getPoints();
        
        return this;
      }
      /**
       * <code>required string points = 6;</code>
       */
      public Builder setPointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        points_ = value;
        
        return this;
      }

      private java.lang.Object receivables_ = "";
      /**
       * <code>required string receivables = 7;</code>
       */
      public boolean hasReceivables() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string receivables = 7;</code>
       */
      public java.lang.String getReceivables() {
        java.lang.Object ref = receivables_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receivables_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receivables = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReceivablesBytes() {
        java.lang.Object ref = receivables_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receivables_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receivables = 7;</code>
       */
      public Builder setReceivables(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        receivables_ = value;
        
        return this;
      }
      /**
       * <code>required string receivables = 7;</code>
       */
      public Builder clearReceivables() {
        bitField0_ = (bitField0_ & ~0x00000040);
        receivables_ = getDefaultInstance().getReceivables();
        
        return this;
      }
      /**
       * <code>required string receivables = 7;</code>
       */
      public Builder setReceivablesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        receivables_ = value;
        
        return this;
      }

      private java.lang.Object proceeds_ = "";
      /**
       * <code>required string proceeds = 8;</code>
       */
      public boolean hasProceeds() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string proceeds = 8;</code>
       */
      public java.lang.String getProceeds() {
        java.lang.Object ref = proceeds_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            proceeds_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string proceeds = 8;</code>
       */
      public com.google.protobuf.ByteString
          getProceedsBytes() {
        java.lang.Object ref = proceeds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proceeds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string proceeds = 8;</code>
       */
      public Builder setProceeds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        proceeds_ = value;
        
        return this;
      }
      /**
       * <code>required string proceeds = 8;</code>
       */
      public Builder clearProceeds() {
        bitField0_ = (bitField0_ & ~0x00000080);
        proceeds_ = getDefaultInstance().getProceeds();
        
        return this;
      }
      /**
       * <code>required string proceeds = 8;</code>
       */
      public Builder setProceedsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        proceeds_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PaymentReq)
    }

    static {
      defaultInstance = new PaymentReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PaymentReq)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
