// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/data/PaymentResp.proto

package com.bhz.eps.msg;

public final class PaymentRespProto {
  private PaymentRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PaymentRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PaymentResp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string stationCode = 1;</code>
     */
    boolean hasStationCode();
    /**
     * <code>required string stationCode = 1;</code>
     */
    java.lang.String getStationCode();
    /**
     * <code>required string stationCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStationCodeBytes();

    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    boolean hasNozzleNumber();
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    int getNozzleNumber();

    /**
     * <code>required string workOrder = 3;</code>
     */
    boolean hasWorkOrder();
    /**
     * <code>required string workOrder = 3;</code>
     */
    java.lang.String getWorkOrder();
    /**
     * <code>required string workOrder = 3;</code>
     */
    com.google.protobuf.ByteString
        getWorkOrderBytes();

    /**
     * <code>required .PaymentResp.Result result = 4;</code>
     */
    boolean hasResult();
    /**
     * <code>required .PaymentResp.Result result = 4;</code>
     */
    com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result getResult();
  }
  /**
   * Protobuf type {@code PaymentResp}
   */
  public static final class PaymentResp extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:PaymentResp)
      PaymentRespOrBuilder {
    // Use PaymentResp.newBuilder() to construct.
    private PaymentResp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PaymentResp(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final PaymentResp defaultInstance;
    public static PaymentResp getDefaultInstance() {
      return defaultInstance;
    }

    public PaymentResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private PaymentResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stationCode_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nozzleNumber_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              workOrder_ = bs;
              break;
            }
            case 34: {
              com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PaymentResp> PARSER =
        new com.google.protobuf.AbstractParser<PaymentResp>() {
      public PaymentResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentResp> getParserForType() {
      return PARSER;
    }

    public interface ResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PaymentResp.Result)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>required string resultCode = 1;</code>
       */
      boolean hasResultCode();
      /**
       * <code>required string resultCode = 1;</code>
       */
      java.lang.String getResultCode();
      /**
       * <code>required string resultCode = 1;</code>
       */
      com.google.protobuf.ByteString
          getResultCodeBytes();

      /**
       * <code>optional string errorCause = 2;</code>
       */
      boolean hasErrorCause();
      /**
       * <code>optional string errorCause = 2;</code>
       */
      java.lang.String getErrorCause();
      /**
       * <code>optional string errorCause = 2;</code>
       */
      com.google.protobuf.ByteString
          getErrorCauseBytes();
    }
    /**
     * Protobuf type {@code PaymentResp.Result}
     */
    public static final class Result extends
        com.google.protobuf.GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:PaymentResp.Result)
        ResultOrBuilder {
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Result(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

      private static final Result defaultInstance;
      public static Result getDefaultInstance() {
        return defaultInstance;
      }

      public Result getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.ByteString unknownFields;
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.ByteString.Output unknownFieldsOutput =
            com.google.protobuf.ByteString.newOutput();
        com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
            com.google.protobuf.CodedOutputStream.newInstance(
                unknownFieldsOutput);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                resultCode_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                errorCause_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          try {
            unknownFieldsCodedOutput.flush();
          } catch (java.io.IOException e) {
          // Should not happen
          } finally {
            unknownFields = unknownFieldsOutput.toByteString();
          }
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<Result> PARSER =
          new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int RESULTCODE_FIELD_NUMBER = 1;
      private java.lang.Object resultCode_;
      /**
       * <code>required string resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public java.lang.String getResultCode() {
        java.lang.Object ref = resultCode_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultCode_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultCodeBytes() {
        java.lang.Object ref = resultCode_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ERRORCAUSE_FIELD_NUMBER = 2;
      private java.lang.Object errorCause_;
      /**
       * <code>optional string errorCause = 2;</code>
       */
      public boolean hasErrorCause() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errorCause = 2;</code>
       */
      public java.lang.String getErrorCause() {
        java.lang.Object ref = errorCause_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorCause_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string errorCause = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCauseBytes() {
        java.lang.Object ref = errorCause_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        resultCode_ = "";
        errorCause_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasResultCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getResultCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getErrorCauseBytes());
        }
        output.writeRawBytes(unknownFields);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getResultCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getErrorCauseBytes());
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code PaymentResp.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result, Builder>
          implements
          // @@protoc_insertion_point(builder_implements:PaymentResp.Result)
          com.bhz.eps.msg.PaymentRespProto.PaymentResp.ResultOrBuilder {
        // Construct using com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          resultCode_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          errorCause_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result getDefaultInstanceForType() {
          return com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance();
        }

        public com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result build() {
          com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result buildPartial() {
          com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result result = new com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.resultCode_ = resultCode_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.errorCause_ = errorCause_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result other) {
          if (other == com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance()) return this;
          if (other.hasResultCode()) {
            bitField0_ |= 0x00000001;
            resultCode_ = other.resultCode_;
            
          }
          if (other.hasErrorCause()) {
            bitField0_ |= 0x00000002;
            errorCause_ = other.errorCause_;
            
          }
          setUnknownFields(
              getUnknownFields().concat(other.unknownFields));
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResultCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object resultCode_ = "";
        /**
         * <code>required string resultCode = 1;</code>
         */
        public boolean hasResultCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string resultCode = 1;</code>
         */
        public java.lang.String getResultCode() {
          java.lang.Object ref = resultCode_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              resultCode_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string resultCode = 1;</code>
         */
        public com.google.protobuf.ByteString
            getResultCodeBytes() {
          java.lang.Object ref = resultCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            resultCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string resultCode = 1;</code>
         */
        public Builder setResultCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          resultCode_ = value;
          
          return this;
        }
        /**
         * <code>required string resultCode = 1;</code>
         */
        public Builder clearResultCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          resultCode_ = getDefaultInstance().getResultCode();
          
          return this;
        }
        /**
         * <code>required string resultCode = 1;</code>
         */
        public Builder setResultCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          resultCode_ = value;
          
          return this;
        }

        private java.lang.Object errorCause_ = "";
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public boolean hasErrorCause() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public java.lang.String getErrorCause() {
          java.lang.Object ref = errorCause_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              errorCause_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public com.google.protobuf.ByteString
            getErrorCauseBytes() {
          java.lang.Object ref = errorCause_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            errorCause_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public Builder setErrorCause(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          errorCause_ = value;
          
          return this;
        }
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public Builder clearErrorCause() {
          bitField0_ = (bitField0_ & ~0x00000002);
          errorCause_ = getDefaultInstance().getErrorCause();
          
          return this;
        }
        /**
         * <code>optional string errorCause = 2;</code>
         */
        public Builder setErrorCauseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          errorCause_ = value;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:PaymentResp.Result)
      }

      static {
        defaultInstance = new Result(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:PaymentResp.Result)
    }

    private int bitField0_;
    public static final int STATIONCODE_FIELD_NUMBER = 1;
    private java.lang.Object stationCode_;
    /**
     * <code>required string stationCode = 1;</code>
     */
    public boolean hasStationCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string stationCode = 1;</code>
     */
    public java.lang.String getStationCode() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stationCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stationCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStationCodeBytes() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOZZLENUMBER_FIELD_NUMBER = 2;
    private int nozzleNumber_;
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    public boolean hasNozzleNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 nozzleNumber = 2;</code>
     */
    public int getNozzleNumber() {
      return nozzleNumber_;
    }

    public static final int WORKORDER_FIELD_NUMBER = 3;
    private java.lang.Object workOrder_;
    /**
     * <code>required string workOrder = 3;</code>
     */
    public boolean hasWorkOrder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string workOrder = 3;</code>
     */
    public java.lang.String getWorkOrder() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          workOrder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string workOrder = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWorkOrderBytes() {
      java.lang.Object ref = workOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result result_;
    /**
     * <code>required .PaymentResp.Result result = 4;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .PaymentResp.Result result = 4;</code>
     */
    public com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result getResult() {
      return result_;
    }

    private void initFields() {
      stationCode_ = "";
      nozzleNumber_ = 0;
      workOrder_ = "";
      result_ = com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStationCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNozzleNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorkOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, nozzleNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, result_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStationCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nozzleNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWorkOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, result_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.eps.msg.PaymentRespProto.PaymentResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.eps.msg.PaymentRespProto.PaymentResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PaymentResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.eps.msg.PaymentRespProto.PaymentResp, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:PaymentResp)
        com.bhz.eps.msg.PaymentRespProto.PaymentRespOrBuilder {
      // Construct using com.bhz.eps.msg.PaymentRespProto.PaymentResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stationCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nozzleNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        workOrder_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp getDefaultInstanceForType() {
        return com.bhz.eps.msg.PaymentRespProto.PaymentResp.getDefaultInstance();
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp build() {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.eps.msg.PaymentRespProto.PaymentResp buildPartial() {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp result = new com.bhz.eps.msg.PaymentRespProto.PaymentResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stationCode_ = stationCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nozzleNumber_ = nozzleNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workOrder_ = workOrder_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.eps.msg.PaymentRespProto.PaymentResp other) {
        if (other == com.bhz.eps.msg.PaymentRespProto.PaymentResp.getDefaultInstance()) return this;
        if (other.hasStationCode()) {
          bitField0_ |= 0x00000001;
          stationCode_ = other.stationCode_;
          
        }
        if (other.hasNozzleNumber()) {
          setNozzleNumber(other.getNozzleNumber());
        }
        if (other.hasWorkOrder()) {
          bitField0_ |= 0x00000004;
          workOrder_ = other.workOrder_;
          
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStationCode()) {
          
          return false;
        }
        if (!hasNozzleNumber()) {
          
          return false;
        }
        if (!hasWorkOrder()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        if (!getResult().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.eps.msg.PaymentRespProto.PaymentResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.eps.msg.PaymentRespProto.PaymentResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationCode_ = "";
      /**
       * <code>required string stationCode = 1;</code>
       */
      public boolean hasStationCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public java.lang.String getStationCode() {
        java.lang.Object ref = stationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stationCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStationCodeBytes() {
        java.lang.Object ref = stationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder setStationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder clearStationCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationCode_ = getDefaultInstance().getStationCode();
        
        return this;
      }
      /**
       * <code>required string stationCode = 1;</code>
       */
      public Builder setStationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stationCode_ = value;
        
        return this;
      }

      private int nozzleNumber_ ;
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public boolean hasNozzleNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public int getNozzleNumber() {
        return nozzleNumber_;
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public Builder setNozzleNumber(int value) {
        bitField0_ |= 0x00000002;
        nozzleNumber_ = value;
        
        return this;
      }
      /**
       * <code>required int32 nozzleNumber = 2;</code>
       */
      public Builder clearNozzleNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nozzleNumber_ = 0;
        
        return this;
      }

      private java.lang.Object workOrder_ = "";
      /**
       * <code>required string workOrder = 3;</code>
       */
      public boolean hasWorkOrder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public java.lang.String getWorkOrder() {
        java.lang.Object ref = workOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            workOrder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWorkOrderBytes() {
        java.lang.Object ref = workOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder setWorkOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder clearWorkOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workOrder_ = getDefaultInstance().getWorkOrder();
        
        return this;
      }
      /**
       * <code>required string workOrder = 3;</code>
       */
      public Builder setWorkOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        workOrder_ = value;
        
        return this;
      }

      private com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result result_ = com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance();
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result getResult() {
        return result_;
      }
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public Builder setResult(com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public Builder setResult(
          com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.Builder builderForValue) {
        result_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public Builder mergeResult(com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            result_ != com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance()) {
          result_ =
            com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .PaymentResp.Result result = 4;</code>
       */
      public Builder clearResult() {
        result_ = com.bhz.eps.msg.PaymentRespProto.PaymentResp.Result.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PaymentResp)
    }

    static {
      defaultInstance = new PaymentResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PaymentResp)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
